# Site settings
author: Jay
title: My Coding Journey
header-img: img/home-bg.png
email: 253jay@gmail.com
copyright_name: Jay
description: > # this means to ignore newlines until "baseurl:"
  Fun times
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  253Jay

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
